// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv7hKkOlPScXQMkbyK_CFmt33Ub96TMMk',
    appId: '1:668498315265:web:97f41ae37290c8424b1800',
    messagingSenderId: '668498315265',
    projectId: 'agora-3d5e6',
    authDomain: 'agora-3d5e6.firebaseapp.com',
    storageBucket: 'agora-3d5e6.appspot.com',
    measurementId: 'G-LX89RWWBJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKaqb6kDuSc1irDuH32xln3lcZOOkyP6k',
    appId: '1:668498315265:android:0704e6e5b7724bf34b1800',
    messagingSenderId: '668498315265',
    projectId: 'agora-3d5e6',
    storageBucket: 'agora-3d5e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkGt-oFJDcg99TP5HfdsiTgc6rE1U2Hww',
    appId: '1:668498315265:ios:085825c1b6ea9c1f4b1800',
    messagingSenderId: '668498315265',
    projectId: 'agora-3d5e6',
    storageBucket: 'agora-3d5e6.appspot.com',
    iosBundleId: 'com.example.agora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkGt-oFJDcg99TP5HfdsiTgc6rE1U2Hww',
    appId: '1:668498315265:ios:085825c1b6ea9c1f4b1800',
    messagingSenderId: '668498315265',
    projectId: 'agora-3d5e6',
    storageBucket: 'agora-3d5e6.appspot.com',
    iosBundleId: 'com.example.agora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv7hKkOlPScXQMkbyK_CFmt33Ub96TMMk',
    appId: '1:668498315265:web:3208251912c130e54b1800',
    messagingSenderId: '668498315265',
    projectId: 'agora-3d5e6',
    authDomain: 'agora-3d5e6.firebaseapp.com',
    storageBucket: 'agora-3d5e6.appspot.com',
    measurementId: 'G-96SZPNCYMM',
  );

}